[phases.build]
nixPkgs = ['...', 'mold', 'glibc']
cmds = ['mkdir -p bin', 'RUSTFLAGS="-C link-arg=-fuse-ld=mold" cargo build --release', 'cp target/release/forum_meucci bin/']

[start]
cmd = './bin/forum_meucci'
